//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace podgotovkaDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.product = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string supplier { get; set; }
        public Nullable<int> qty_in_pack { get; set; }
        public string unit { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> stock_qty { get; set; }
        public Nullable<int> min_qty { get; set; }
        public Nullable<int> material_type_id { get; set; }
        public Nullable<int> warehouses_id { get; set; }
    
        public virtual a material_type { get; set; }
        public virtual warehouses warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
    }
}
